#!/bin/sh
UPDATE_VERSION=1.0.0
export PATH="/mnt/SDCARD/System/bin:/mnt/SDCARD/bin:/mnt/SDCARD/System/usr/trimui/scripts:$PATH"
export LD_LIBRARY_PATH="/mnt/SDCARD/System/lib:/usr/trimui/lib:$LD_LIBRARY_PATH"

# Shared device helpers: enable_wifi, check_available_space, download_file, ...
. /mnt/SDCARD/System/usr/trimui/scripts/common_functions.sh

if [ "$1" = "-v" ]; then
    echo -n $UPDATE_VERSION
    exit
fi

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
PURPLE='\033[01;35m'
NC='\033[0m' # No Color

GITHUB_REPOSITORY=jukaLang/JukaMix-OS
updatedir="/mnt/SDCARD/System/updates"
Local_JukaMixVersion="$(cat "/mnt/SDCARD/System/usr/trimui/jukamix-version.txt")"
current_date=$(date "+%Y-%m-%d")
timestamp=$(date +'%Y%m%d-%Hh%M')

# Convert x.y.z[.w][-suffix] into a comparable integer.
get_version() {
    echo "$1" | tr -d '[:alpha:]' | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'
}

check_connection() {
    echo -n "Checking internet connection... "
    if wget -q --spider https://github.com >/dev/null; then
        echo -e "${GREEN}OK${NC}"
    else
        echo -e "${RED}FAIL${NC}\nError: https://github.com not reachable. Check your wifi connection."
        echo -ne "${YELLOW}"
        read -n 1 -s -r -p "Press A to exit"
        exit 2
    fi
}

check_filesystem() {
    echo -e "\n${BLUE}================== CHECKDISK ==================${NC}\n"

    force=0
    if [ "$1" = "--force" ]; then
        force=1
    fi

    # Check the filesystem
    last_fsck_date=$(cat /mnt/SDCARD/System/updates/last_fsck.txt 2>/dev/null)

    if [ "$force" -eq 0 ] && [ "$last_fsck_date" = "$current_date" ]; then
        echo -e "The last fsck was performed today ($current_date).\nNo need to rerun."
    else
        echo -ne "\n" \
            "Please wait during FAT file system integrity check.\n" \
            "Issues should be fixed automatically.\n" \
            "The process can be long:\n" \
            "about 2 minutes for 128GB SD card\n\n"

        mount_point=$(mount | grep -m 1 '/mnt/SDCARD' | awk '{print $1}')
        /mnt/SDCARD/System/bin/fsck.fat -a "$mount_point" 2>&1 | awk 'NR > 3'

        echo "$current_date" >/mnt/SDCARD/System/updates/last_fsck.txt

        if ls /mnt/SDCARD/FSCK*.REC 1>/dev/null 2>&1; then
            rec_dir="/mnt/SDCARD/rec_files"
            mkdir -p "$rec_dir"
            mv /mnt/SDCARD/FSCK*.REC "$rec_dir"
            echo "FSCK*.REC files moved to $rec_dir"

            cat >"$rec_dir/_description.txt" <<EOL
The files with the extension .REC are recovery files generated by the fsck.fat tool during a file system integrity check.
These files are created when the tool encounters potential issues with the file system. 
They may contain data that was recovered or repaired. In general, these files can be ignored if no issues are noticed with the system.
However, they may also contain partial or deleted data that may not be fully usable.
You can safely delete them if you're sure the file system is working properly.
EOL
        fi
    fi
}
